import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { Medication, Prescription, PatientInfo, Doctor } from '@/types';

interface PrescriptionPDFData {
  doctor: Doctor;
  patient: PatientInfo;
  prescription: Prescription;
  medications: Medication[];
  date: string;
}

/**
 * Generate a clean prescription PDF client-side using jsPDF.
 * Returns the PDF as a Blob.
 */
export function generatePrescriptionPDF(data: PrescriptionPDFData): Blob {
  const { doctor, patient, prescription, medications, date } = data;
  const doc = new jsPDF({ unit: 'mm', format: 'a5' });
  const pageWidth = doc.internal.pageSize.getWidth();

  // ── Clinic Header ───────────────────────────
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(doctor.clinic_name || 'Clinic', pageWidth / 2, 14, { align: 'center' });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const doctorLine = 'Dr. ' + doctor.full_name + (doctor.mci_number ? ' | MCI: ' + doctor.mci_number : '');
  doc.text(doctorLine, pageWidth / 2, 20, { align: 'center' });

  // ── Separator ───────────────────────────────
  doc.setDrawColor(0, 102, 204);
  doc.setLineWidth(0.5);
  doc.line(10, 24, pageWidth - 10, 24);

  // ── Patient Info ────────────────────────────
  let y = 30;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Patient: ' + patient.name, 10, y);
  doc.text('Date: ' + date, pageWidth - 10, y, { align: 'right' });
  y += 5;
  doc.setFont('helvetica', 'normal');
  const ageGender = [
    patient.age ? 'Age: ' + patient.age : null,
    patient.gender ? 'Gender: ' + patient.gender : null,
  ].filter(Boolean).join(' | ');
  if (ageGender) {
    doc.text(ageGender, 10, y);
    y += 5;
  }
  doc.text('Phone: ' + patient.phone, 10, y);
  y += 6;

  // ── Diagnosis ───────────────────────────────
  if (prescription.diagnosis) {
    doc.setFont('helvetica', 'bold');
    doc.text('Diagnosis:', 10, y);
    doc.setFont('helvetica', 'normal');
    doc.text(prescription.diagnosis, 32, y);
    y += 6;
  }

  // ── Rx Symbol ───────────────────────────────
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 102, 204);
  doc.text('\u211E', 10, y + 2);
  doc.setTextColor(0, 0, 0);
  y += 6;

  // ── Medications Table ───────────────────────
  if (medications.length > 0) {
    autoTable(doc, {
      startY: y,
      margin: { left: 10, right: 10 },
      head: [['#', 'Medicine', 'Dosage', 'Freq', 'Duration', 'Timing']],
      body: medications.map((med, i) => [
        String(i + 1),
        med.display_name,
        med.dosage || '-',
        med.frequency || '-',
        med.duration || '-',
        med.timing || '-',
      ]),
      styles: { fontSize: 9, cellPadding: 2 },
      headStyles: { fillColor: [0, 102, 204], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [240, 245, 255] },
    });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 6;
  }

  // ── Instructions ────────────────────────────
  if (prescription.instructions && prescription.instructions.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Instructions:', 10, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    prescription.instructions.forEach((inst) => {
      doc.text('\u2022 ' + inst, 14, y);
      y += 4.5;
    });
    y += 2;
  }

  // ── Follow-up ───────────────────────────────
  if (prescription.follow_up) {
    doc.setFont('helvetica', 'bold');
    doc.text('Follow-up:', 10, y);
    doc.setFont('helvetica', 'normal');
    doc.text(prescription.follow_up, 32, y);
    y += 6;
  }

  // ── Tests ───────────────────────────────────
  if (prescription.tests_ordered && prescription.tests_ordered.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.text('Tests Ordered:', 10, y);
    doc.setFont('helvetica', 'normal');
    doc.text(prescription.tests_ordered.join(', '), 38, y);
    y += 6;
  }

  // ── Footer ──────────────────────────────────
  const footerY = doc.internal.pageSize.getHeight() - 12;
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text(
    'This prescription was reviewed and approved by the prescribing doctor. Generated by DocScribe.',
    pageWidth / 2,
    footerY,
    { align: 'center' },
  );
  doc.text('Dr. ' + doctor.full_name, pageWidth - 10, footerY + 4, { align: 'right' });

  return doc.output('blob');
}

/**
 * Trigger a download of the PDF blob in the browser.
 */
export function downloadPDF(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
